### ISSUE TITLE
Joint SIMD meeting on 2021-04-16

### ISSUE THREAD

**Issue by penzn** [WebAssembly/flexible-vectors#31]
It has been decided to adopt old Wasm SIMD meeting slot for discussions on both relaxied-simd and this proposal.

It is going to happen on Apr 16th if my calculations are correct:

https://github.com/WebAssembly/simd/issues/477#issuecomment-802975140

Calling for agenda items and participants.

**Comment by ngzhian** [comment]
I think it should be 2021-04-16.

**Comment by penzn** [comment]
You are right, I was off by one week.

**Comment by ngzhian** [comment]
I think we can cancel this, since we have no agenda items, and it is < 24 hours till this meeting.

**Comment by penzn** [comment]
It should be fine to cancel; sorry, forgot to hit "Comment" again. Taking inspiration from other subgroups, maybe we can try to expand the scope beyond two new proposals and look for more forward-looking presentations. For example new architectures and toolchains or ideas beyond what we are willing to entertain in near term.

**Comment by ngzhian** [comment]
Yea talking about new ideas sgtm!

**Comment by penzn** [comment]
Let's try this next time, I'll call on some people here and you and @Maratyszcza can think about what you want to present as well.
