### ISSUE TITLE
sub/div opcode clash

### ISSUE THREAD

**Issue by pannous** [WebAssembly/flexible-vectors#54]
BinaryFlexibleVectors.md

contains a mistake:

sub/div clash by both occupying opcode 0x95

vec.f32.sub | 0x76 | 0x95 | -
vec.f64.sub | 0x75 | 0x95 | -
vec.f32.div | 0x76 | 0x95 | -
vec.f64.div | 0x75 | 0x95 |  

also the integer version of div is missing:

vec.i64.sub | 0x77 | 0x31 | -
vec.i8.mul | 0x7A | 0x32 | -

https://github.com/WebAssembly/flexible-vectors/blob/main/proposals/flexible-vectors/BinaryFlexibleVectors.md

**Comment by penzn** [comment]
Good catch, thank you!

Integer division was omitted on purpose - it is not present in simd128 either.
